# Generated by Django 4.2.7 on 2023-11-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.area'),
        ),
        migrations.AlterField(
            model_name='country',
            name='korean_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
